# Nome da aplicação e porta
spring.application.name=distribuidora-api
server.port=8080

# ===============================
# CONFIGURAÇÕES DO BANCO DE DADOS (MySQL)
# ===============================
# O 'distribuidora_db' é o nome do schema que você precisa criar no seu MySQL (CREATE DATABASE distribuidora_db;)
spring.datasource.url=jdbc:mysql://localhost:3306/distribuidora_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=senaisp
#andremendes é a senha do pc pessoal
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CONFIGURAÇÕES DO JPA / HIBERNATE
# ===============================
# update: Cria ou atualiza as tabelas automaticamente com base nas nossas classes @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# CONFIGURAÇÃO DO JWT
# ===============================
api.security.token.secret=chave-super-secreta-distribuidora-12345
